### ISSUE TITLE
Deduplicate words from tags

### ISSUE THREAD

**Issue by aleksejrs** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#12]

**Comment by thiswillbeyourgithub** [comment]
Details please

**Comment by aleksejrs** [comment]
> emotions nauseous hard answerisdrawing in mix emotions nauseous list

One "emotions nauseous" is from a normal tag, and other is from a `relation-` tag connecting several notes. Though maybe it makes sense in this case; but it may not in some other case.

**Comment by thiswillbeyourgithub** [comment]
I will not implement this. TF-IDF is actually *counting* words and I don't want to mess with it.

If you want to do this yourself, deduplicating a list is as simple as `tags = list(set(tags))`
