### ISSUE TITLE
Implementing a frequency list for language learning

### ISSUE THREAD

**Issue by ghost** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#16]
Hey!
Maybe this is out of your interest but, as a language learner it is very important to acquire the most used words/vocabulary of a language and build from that point on by learning from a set of frequency words. These words are the most used in a language and can be found on wiktionary:
`https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists`

When I start learning a language I first learn these words and then move on to sentences which contain these words.
Wondering if this can somehow be implemented in this addon by supplying a list of "must contain these words" list as a text file, to tell the addon "hey, this is priority number one" and check which of my cards contain these words. They're ordered from 1->most frequent to for example 2000-> least used.

Maybe this is of no interest to you, but I know a few people that learn languages this way and it would be a game changer!
Anyways, if you're interested I could send you a frequency.txt file in a few languages for you to try out or you could just check out that website.
Have a great day and thanks for reading!

**Comment by thiswillbeyourgithub** [comment]
Hi,

wouldn't it be way simpler to just create a deck by order of frequency?

Btw thanks for the link, I didn't know wiki had such an exhaustive list of frequency lists!

**Comment by ghost** [comment]
Yes, that's what I've been doing and I noticed that, after doing what I discussed in my other issue, this isn't necessary anymore because different cards are already showing up. So the variation is excellent for acquiring new sentence patterns :D
