### ISSUE TITLE
Do not use collections in Trash

### ISSUE THREAD

**Issue by aleksejrs** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#18]
I added the cache path fix and noticed this:

> Ankipandas will use anki collection found at /home/fc/.local/share/Trash/files/gfgsgf/collection.anki2

Note that vifm's trash directory is `~/.local/share/vifm/Trash`

**Comment by thiswillbeyourgithub** [comment]
Hi!

Thanks for using AnnA :)

I looked into it and this is a frequent issue wih ankipandas. I'd rather not fail directly if trash is found so I added a delay + warning with sound notification. What do you think?

It's in 6d47c60

**Comment by thiswillbeyourgithub** [comment]
update : I made a mistake that I fixed this morning at 5cfc783afccbc1b0275382138c0afb3842e18431
