### ISSUE TITLE
Negative improvement ratio all the time since updates

### ISSUE THREAD

**Issue by aleksejrs** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#19]
I updated most of my Debian from stable to testing, and updated AnnA. Now the improvement ratio is negative all the time, as bad as -5 or -8. Is it still working?

**Comment by thiswillbeyourgithub** [comment]
Hi!

Are you using the master branch or the dev branch?

**Comment by aleksejrs** [comment]
Hi. The main branch.

**Comment by thiswillbeyourgithub** [comment]
I'm using the dev branch and know that it's definitely working (using it every morning) but there were a number of changes, most importantly the vectorizer is UMAP instead of TFIDF and I added a 2D embedding plotter.

Would you mind testing the dev branch, reading each new argument's doc and trying it out ? I would rather not merge it before I wrote the documentation for the embedding etc :/

Also, keep in mind that a negative ratio does not necessarily mean that it failed. I added a "boost" mechanism that allows to boost cards that are really way overdue and AnnA can prioritize them over reducing the overall distance. All of this can be adjusted in the arguments.

**Comment by aleksejrs** [comment]
The `append_tags` is not in the example autorun file.
`tags_separator` argument was removed, but still is in the README.
There is a "Wether" in the README.

```
Selected deck: /::s

Will use GPT as tokenizer.
Syncing before execution...
NOTIF: /::s: unsupported action
Traceback (most recent call last):
  File "/AnnA_Anki_neuronal_Appendix/./autorun.py", line 19, in <module>
    AnnA(deckname="/::s",
  File "/AnnA_Anki_neuronal_Appendix/AnnA.py", line 635, in __init__
    sync_output = self._call_anki(action="sync")
  File "/AnnA_Anki_neuronal_Appendix/AnnA.py", line 730, in _call_anki
    raise Exception(response['error'])
Exception: unsupported action
```

Anki 2.1.22.

After reverting to the main branch and burying everything except for 100 cards, I finally got +0.8%, and with 25 cards, +4.3%.

**Comment by thiswillbeyourgithub** [comment]
> The `append_tags` is not in the example autorun file. `tags_separator` argument was removed, but still is in the README. There is a "Wether" in the README.

* The autorun example file is not meant to showcase every argument. Am I missing something?
* I just updated the arguments pasted in the README
* I fixed the wether typo (thanks a lot!)

> 
> ```
> Selected deck: /::s
> 
> Will use GPT as tokenizer.
> Syncing before execution...
> NOTIF: /::s: unsupported action
> Traceback (most recent call last):
>   File "/AnnA_Anki_neuronal_Appendix/./autorun.py", line 19, in <module>
>     AnnA(deckname="/::s",
>   File "/AnnA_Anki_neuronal_Appendix/AnnA.py", line 635, in __init__
>     sync_output = self._call_anki(action="sync")
>   File "/AnnA_Anki_neuronal_Appendix/AnnA.py", line 730, in _call_anki
>     raise Exception(response['error'])
> Exception: unsupported action
> ```

The 'unsupported action' error means that you have not updated the companion plugin. I added a more informative error message in ... the updated addon.
 
> Anki 2.1.22.

I'm using 2.1.49. May I ask the reason why you're still on such an old release?

**Comment by aleksejrs** [comment]
Newer versions of Anki are much slower with tags, and I use very long queries to add priority tags, so it can take minutes there.

I also use [Cardistry](https://github.com/lovac42/Cardistry), [modified to give the harder cards more weight](https://github.com/aleksejrs/myankiaddoncustomizations21).

One more reason is obsolete now.

**Comment by thiswillbeyourgithub** [comment]
I think recent versions were more focused on performance so you might want to try more recent versions.

I'll close this for now but don't hesitate to open one again if you encounter any issue or have any question!

**Comment by aleksejrs** [comment]
The performance improvements mentioned in the changelog seem irrelevant to tag searches, and Cardistry will become relevant again once I get rid of the backlog.
