### ISSUE TITLE
Link cards with same keyword?

### ISSUE THREAD

**Issue by ghost** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#2]
Hi! Hope you're doing okay :)

So what I’ve been wondering is:
If I have a card which contains a word in the Expression field, for example **Eat**.
Is it possible to show all cards which contain this word in their field and parse/link them into another field in the card where Eat is?
For example:
FieldCard**1**–>Expression: Eat
FieldCard**2**–>Expression: I like to **eat** apples
FieldCard**3**–>Expression: He doesn’t **eat** apples

FieldCard**1**–>Sentences: I like to eat apples | He doesn’t eat apples

I have a special field which shows me the focused word of each note, so there are many Eats, drinks and go's. Sorting and learning is impractical because of the sheer amount of notes that would make me have to learn....

This is especially useful if one has many sentences which are correlated and make sense to learn. So one could just see many examples in one note and super-expose oneself to the keyword.

If this is possible I’d greatly appreciate your help! Thanks

**Comment by thiswillbeyourgithub** [comment]
Hi!

Sorry for getting to answer only today, I was busy as hell :) but I'm very glad you're interested in AnnA.

I'm not sure I understand, are you only interested in *grouping* cards by common meaning for the sake of organization? Or are you interested in making sure that you won't have multiple reviews on the same day that are dealing with the same specific topic?

Both seem to be already possible but I want to make sure I understand what you're trying to accomplish first :)

**Comment by ghost** [comment]
Hey! Yep, both of those are what I'm looking for. Ideally what I'd like is to be able to see all related, relevant cards to the one I'm just studying. Like a field in which where one has example sentences for a specific word. I'd then have usage reference of Eat without having to study all Eat cards, because I'd have enough usage reference. Just don't know how to do this...if it's something that can be done that would be awesome!

**Comment by thiswillbeyourgithub** [comment]
Okay then for the study part of your question : definitely possible, it's basically why I made AnnA

For the organization part : what you can do is use the index task with clusterization to automatically add to each card a tag indicating cluster of food / eating related cards. Unfortunately you can't really do more than that I'm afraid.

I deliberately made those instructions a *bit* vague to see if my documentation is clear enough to make you achieve the desired results.

Btw I merged the dev branch this morning so I'm hoping I've not let any outdated bits in the README but I don't have time to check really.

Don't hesitate to come back and reopen this if you're having any issues :)
