### ISSUE TITLE
Numpy wheels Python 3.10

### ISSUE THREAD

**Issue by ghost** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#4]
The necessary wheels for numpy on python 3.10 fail to install when trying to install with `pip install -r requirements.txt` and also, on Manjaro/Arch the package pdb isn't available 😢

**Comment by thiswillbeyourgithub** [comment]
Hi!

Thanks for the interest in this :)

* fixed the typo : (txt <- py)
* removed pdb from requirements.txt : it's actually built in so no need to install it
* regarding building numpy on 3.10, I'm using python 3.9.0. Would you mind trying with python 3.9.0 and telling me if it works better?

**Comment by ghost** [comment]
Yep! I'll try that and report back :)

**Comment by thiswillbeyourgithub** [comment]
Closing in the mean time :)
