### ISSUE TITLE
Exception: 'Scheduler' object has no attribute 'rebuild_filtered_deck' (Anki 2.1.22)

### ISSUE THREAD

**Issue by aleksejrs** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#8]
```
Improvement ratio:
       _  ___   __    ___ ______  __
   _  / |/ _ \ / /_  ( _ )___ (_)/ /
 _| |_| | | | | '_ \ / _ \ |_ \ / / 
|_   _| | |_| | (_) | (_) |__) / /_ 
  |_| |_|\___(_)___/ \___/____/_/(_)
                                    

Creating deck containing the cards to review: /::s - AnnA Optideck
Traceback (most recent call last):
  File "/mnt/addons/AnnA_Anki_neuronal_Appendix/./autorun.py", line 15, in <module>
    AnnA(deckname="/::s",
  File "/mnt/addons/AnnA_Anki_neuronal_Appendix/AnnA.py", line 316, in __init__
    self._bury_or_create_filtered()
  File "/mnt/addons/AnnA_Anki_neuronal_Appendix/AnnA.py", line 1318, in _bury_or_create_filtered
    self._call_anki(action="createFilteredDeck",
  File "/mnt/addons/AnnA_Anki_neuronal_Appendix/AnnA.py", line 345, in _call_anki
    raise Exception(response['error'])
Exception: 'Scheduler' object has no attribute 'rebuild_filtered_deck'
```

**Comment by thiswillbeyourgithub** [comment]
What version of anki are you on ?

Have you tried deleting the filtered deck and letting anna create a new one from scratch ? It can't actually rebuild a deck currently.

**Comment by aleksejrs** [comment]
2.1.22. Yes, it creates the deck.

**Comment by thiswillbeyourgithub** [comment]
It creates the deck then issues this error?

**Comment by aleksejrs** [comment]
Yes.

**Comment by thiswillbeyourgithub** [comment]
Is it possible for you to upgrade anki? 2.1.22 is quite old now :/

**Comment by aleksejrs** [comment]
I don't know, there are several problems with that.

I used to have an Anki 2.0 forecasting add-on to find difficult cards ([related](https://github.com/aleksejrs/anki-2.0-card-time-forecast)), but now I added a simplified version to my copy of [Cardistry](https://github.com/lovac42/Cardistry) (so more difficult cards reduce the amount of new cards more), and Cardistry is not supported, so it's probably 2.1.33 max. [Limit new cards based on due + reviews](https://ankiweb.net/shared/info/548158563) is not a complete replacement for Cardistry; I use them together now.

Another add-on I used which doesn't work in the recent versions is [Incremental Reading](https://ankiweb.net/shared/info/935264945), although I stopped for now.

The third problem is with this: https://gitlab.com/aleksejrs/anki-priofiltergenerator I use complex search queries for prioritization. Now that I use Anki 2.1.x (which is slower) and MorphMan (which processes each card separately), I just add/remove tags "morphman_important" and "morphman_urgent" to the search results, but starting Anki 2.1.3x, tag search is a few times slower (I think at least 3, but whatever it was, they told me it would become even slower in 2.1.4x; I don't know if they tried optimizing anything: the problem was that the tag string was split every time a card is checked for a match).

**Comment by aleksejrs** [comment]
Burying is preferable for the old scheduler though, so that I don't have to keep a few filtered decks because of the learning cards: https://docs.ankiweb.net/filtered-decks.html?highlight=filtered%20learn#home-decks
> In the old scheduler, if you create, rebuild, empty, or delete a filtered deck while cards are still in learning, they will be turned back into new cards. In the case of failed reviews in relearning, any remaining relearning steps will be skipped. This was fixed in the v2 scheduler so cards are no longer reset.

**Comment by thiswillbeyourgithub** [comment]
* I'm sorry but I don't plan on trying to support a version as old as 2.1.22 :/
A lot of things changed between then and now and I have no idea if it would actually work so I can't spend time on this. Sorry.

* Regarding incremental reading, I heard good things about [Searching, PDF Reading & Note-Taking in Add Dialog](https://ankiweb.net/shared/info/1781298089)

* Regarding the speed of anki : you might want to try the latest versions as searching is possibly now done in Rust. For my part, I only saw speed up of anki.
You might also want to take a look at [Anki Pandas](https://github.com/klieret/AnkiPandas), with anki connect you could maybe implement your own better search algorithm?
