### ISSUE TITLE
Move the tag ignoring settings to a user-customizable place?

### ISSUE THREAD

**Issue by aleksejrs** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#9]
Anki adds "leech" to difficult cards.
MorphMan adds lots of tags like "mm_comprehension" or "mm_fresh".
Tags like "relation-blabla": "relation" needs to be ignored.
I have some custom tags like "important", "urgent",  "morphman_important" or "morphman_urgent".

**Comment by thiswillbeyourgithub** [comment]
Good suggestion, added in 2e6892a89adbda620ebe4dee461385c6c6ddb20a

I don't have the time to test it so I recklessly pushed it. I would greatly appreciate it if you could reopen this issue if you find an issue with the commit :)

**Comment by aleksejrs** [comment]
I guess it works, thanks. Prefixes would also be useful though, and the word "relation" only appears after splitting.

**Comment by thiswillbeyourgithub** [comment]
What do you mean ?

**Comment by aleksejrs** [comment]
Prefixes: `tag.startswith(("mm_", "morphman-"))`
relations: [Bury related notes](https://ankiweb.net/shared/info/413416269) https://github.com/Arthur-Milchior/anki-relation

**Comment by aleksejrs** [comment]
So cards sharing the same string after "relation-" are **very** related (like siblings, but not in a way Anki would know), but sharing just the word "relation" is nothing but "I have that kind of siblings".

**Comment by thiswillbeyourgithub** [comment]
I don't think handling "relations-XXX" is a good idea.

The whole purpose of AnnA is to find which cards are related automatically. If you use AnnA with low enough settings (say 50% of daily reviews(, and 80% of daily learnings if over multiple days)) it should actually never be a problem.

If two cards are very related but share absolutely no words, phrasing or tags in common then I think you're deck is not very well organized.


Regarding prefixes: I don't understand what you mean

**Comment by aleksejrs** [comment]
> If you use AnnA with low enough settings (say 50% of daily reviews(, and 80% of daily learnings if over multiple days)) it should actually never be a problem.

I don't have a significant backlog now, so I don't really understand.

> If two cards are very related but share absolutely no words, phrasing or tags in common then I think you're deck is not very well organized.

**Conclusion two paragraphs below: okay, that doesn't seem significant.**

The relations appeared before AnnA, and are used for new cards, like [PushParadox](https://github.com/lovac42/PushParadox) does. It's not for fast learning, but it reduces the chances of the AnnA-treated problem appearing in the days between reviews of young cards. Another add-on like that is [Bury Cousins (related cards that aren't siblings)](https://ankiweb.net/shared/info/1072815885)

The potential problem is that — if AnnA's effect can be positive, can it also be negative (e.g., if I reviewed many important cards on one day, it might try hiding important cards from me the next day, just because they all have "important" and "frequency" tags)? — the  meta tags may make a significant part of those words, for example in Image Occlusion or image-name cards. An image-name card is often just an image (1), two words (3), a year (4), a tag (6), and a relation tag (8) and the word "relation" is 1/8 of all words. An image-age card may be missing a name, but then "relation" can actually help.

> Regarding prefixes: I don't understand what you mean

Okay, I don't really care if you implement that.
I have 9 meta tags starting with "mm_", 3 tags starting with "morphman-", and many "todo-" tags. I can, of course, add the two former groups manually without a problem, and the third one is pretty much obsolete and is really supposed to be temporary or for suspended cards.

**Comment by thiswillbeyourgithub** [comment]
> The potential problem is that — if AnnA's effect can be positive, can it also be negative (e.g., if I reviewed many important cards on one day, it might try hiding important cards from me the next day, just because they all have "important" and "frequency" tags)? — the meta tags may make a significant part of those words, for example in Image Occlusion or image-name cards. An image-name card is often just an image (1), two words (3), a year (4), a tag (6), and a relation tag (8) and the word "relation" is 1/8 of all words. An image-age card may be missing a name, but then "relation" can actually help.

It's actually not true. Tags are written once whereas fields of your cards are copied as many times as you want.

Hence, if you feel like your image occlusion cards don't have that many words, you can just increase the relative importance of those fields anyway.
